CREATE TABLE IF NOT EXISTS users
(
    id       int generated by default as identity primary key,
    name     varchar(255),
    login    varchar(255) not null,
    birthday date         not null,
    email    varchar(255) not null
);
SELECT *
FROM USERS